### ISSUE TITLE
[feat] 대기 신청 완료 팝업 구현

### ISSUE THREAD

**Issue by HAJIEUN02** [DOSOPT-CDS-TABLING/Tabling-Android#13]
## What is this issue? 🛠
대기 신청 완료 팝업 구현

## Progress 🏃‍♀️
- [x] 커스텀 다이얼로그 구현
- [x] 다이얼로그 호출 테스트
- [x] 버튼 클릭 시 이용완료/예정 뷰로 이동

**Comment by jihyunniiii** [comment]
라벨이랑 등등 지정해주라요
