### ISSUE TITLE
[feat] 지역 인기 매장 뷰 구현

### ISSUE THREAD

**Issue by Doreminwoo** [DOSOPT-CDS-TABLING/Tabling-Android#3]
## What is this issue? 🛠
매장 검색, 지역 인기매장

## Progress 🏃‍♀️
- [x] Top App Bar
  - [x] BackButton 구현 (이전 화면은 없음)
- [x] Chip으로 지역 구분
  - [x]  Chip 클릭 style 변경...
- [x] RecyclerView 매장 구현
  - [x] 대기 팀이 0일 때 Chip Text에 대기없음 이 출력되야 하고 칩 style이 바껴야함
  - [x] dataBinding에서 이미지 처리하기
- [x] 폰트 설정 했는가?
- [x] 텍스트 사이즈 설정 했는가?

**Comment by jihyunniiii** [comment]
지역 인기 매장 뷰 구현하는 거니까 이슈 이름 `[feat] 지역 인기 매장 뷰 구현` 이런 식으로 하는 게 좋을 것 같아요 ! 나중에 같은 뷰의 API 연동도 해야하니까 지금처럼 네이밍 해놓으면 나중에 헷갈릴 것 같숨다 ㅠ
